// LOREM TEXT
const text = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse libero tortor, mollis accumsan ligula sit amet, congue eleifend lectus. Donec feugiat velit ipsum, quis lacinia arcu placerat sodales. Quisque id risus vehicula ligula posuere sagittis sed et justo. Nulla efficitur, neque et placerat dignissim, ex nisl luctus libero, vitae ultrices eros quam sed nibh. Maecenas eu elit vehicula, blandit risus in, vulputate tellus. Phasellus dictum leo ac fringilla suscipit. Aliquam scelerisque purus ut dignissim fermentum. Integer ut commodo ex. Morbi egestas sed ligula eu suscipit. Sed vulputate neque eros, eu blandit ligula sagittis vitae.",
  "Integer sit amet vulputate risus, eget elementum sapien. Nullam mollis dapibus dolor nec sagittis. Nullam a eleifend dolor. In volutpat mattis dui non rutrum. Fusce tincidunt leo ac iaculis tempus. Mauris eu nulla vitae risus posuere bibendum. Aliquam interdum, purus sit amet malesuada mollis, turpis eros blandit orci, et iaculis velit ligula vitae quam. In eleifend tempus tellus, eget hendrerit orci hendrerit nec. Aenean orci tortor, pretium sit amet lobortis mollis, ultricies vitae risus. Etiam in lacinia ante, a mollis neque. Etiam id odio eget orci efficitur venenatis malesuada eu ante. Etiam at ligula sed lacus egestas rutrum. Morbi vitae rhoncus felis. Nullam at lorem malesuada, finibus dui quis, varius felis.",
  "Fusce nec ligula semper, semper quam ac, ultricies enim. Nam at vehicula turpis. Nunc tincidunt justo vel quam iaculis commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris interdum lorem ligula, quis vulputate mauris fringilla a. Nulla eu risus sapien. Nunc mollis tincidunt quam id interdum. In hac habitasse platea dictumst.",
    "Nunc risus quam, pellentesque id blandit sed, condimentum eu ex. Donec molestie rhoncus tortor, placerat aliquet metus luctus at. Integer pharetra mollis diam, eu posuere augue suscipit id. Aenean suscipit malesuada massa, a bibendum elit egestas at. Integer odio libero, auctor vel bibendum vel, pellentesque at arcu. Vestibulum fermentum egestas enim egestas laoreet. Nullam tincidunt volutpat sem, congue pharetra turpis tincidunt non.",
    "Aliquam nunc sem, imperdiet eget mauris non, semper semper nisi. Vestibulum in neque elit. Sed ipsum arcu, blandit et tellus feugiat, ultrices luctus felis. In eu mollis urna. Vivamus sed quam lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras non pellentesque dolor, vitae tempus metus. Fusce metus nunc, accumsan non malesuada accumsan, sodales eget elit.",
    "Fusce ipsum diam, tristique ac faucibus nec, aliquam nec ex. Aliquam at euismod diam, eu molestie purus. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque eget erat id metus vestibulum condimentum. Nunc posuere felis sit amet turpis volutpat volutpat. In aliquet, libero id consequat pretium, sem nisl tempor diam, nec blandit neque ipsum et lectus. Suspendisse facilisis lorem a ante luctus elementum. Donec ac arcu et augue vulputate hendrerit. Sed at ipsum diam. Nunc nulla ligula, efficitur quis nisl sed, semper euismod nisl. Proin pretium felis at turpis efficitur iaculis. Curabitur rhoncus nisi lectus, vitae suscipit sem vulputate et.",
    "Ut feugiat volutpat tortor ac varius. Vivamus non diam vel lorem ornare sagittis. Integer lacinia lobortis lacus, ut cursus ante ultrices vel. Mauris tempor dui nec leo mattis, eget posuere tellus blandit. Donec imperdiet, libero at sodales eleifend, diam metus dignissim eros, in scelerisque quam mauris id nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vel leo neque. Quisque rhoncus leo nunc, semper maximus dolor scelerisque non. Nunc finibus ante varius volutpat ullamcorper.",
    "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin laoreet vitae arcu sit amet mollis. Nam in ante ac lectus dapibus molestie pharetra et nibh. Donec luctus ultricies lectus sed fermentum. Maecenas feugiat magna sed quam commodo rhoncus. Quisque et quam et mauris tincidunt iaculis id vel eros. Vivamus sit amet consequat justo, eu finibus ipsum.",
    "Nulla ac vulputate risus. Aenean non convallis lacus. Cras sodales sapien non quam fringilla rhoncus. Donec vel augue justo. Nunc lectus quam, pellentesque ac magna nec, porttitor facilisis magna. Donec ante ex, ullamcorper eu urna non, scelerisque congue turpis. In quis sagittis lorem. Nam pulvinar purus et consequat viverra. Duis imperdiet enim eget leo ultricies, nec scelerisque neque aliquet. Suspendisse potenti. Cras tortor odio, hendrerit id nibh et, mattis hendrerit erat. Praesent pulvinar placerat lorem a sagittis. Sed quis elit eu erat mattis bibendum in non metus. Fusce consectetur mollis arcu eget vestibulum. Integer vitae mi ut diam condimentum gravida. Nunc laoreet in turpis ut viverra.",
    "Nam ac placerat lacus. Mauris non nulla ac ante faucibus faucibus. Cras ac porttitor tortor, non pulvinar odio. Morbi in ornare mi, ut malesuada sem. Nullam eleifend diam ut orci euismod maximus. Nullam tempus porttitor libero, nec dignissim eros. Proin sed dapibus felis. Donec blandit nibh vitae nisi imperdiet, facilisis lobortis magna egestas. Sed risus justo, condimentum sed metus in, porttitor euismod odio. Phasellus sem mi, viverra vel tristique eu, tempus eleifend lectus. Nam vestibulum nisl vel pharetra vehicula. In rutrum euismod eleifend. In hac habitasse platea dictumst. Etiam eu lectus sit amet sapien venenatis luctus in eget justo. Curabitur aliquet dolor ac erat suscipit, non ultrices nunc molestie. Maecenas semper mi metus, sed eleifend risus venenatis non",
    "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc iaculis odio nulla, non egestas est venenatis in. Pellentesque pretium luctus ipsum vel consectetur. Mauris lectus ipsum, dapibus id malesuada at, sodales nec mi. Mauris justo magna, efficitur non sapien non, efficitur tincidunt nisl. Pellentesque blandit dolor eget lacus ornare accumsan sit amet id tellus. Proin sed mauris bibendum, dapibus ex non, molestie sem. Nulla scelerisque, purus at finibus aliquet, mauris nisi lacinia felis, tincidunt sodales ex urna nec sem. Etiam aliquam accumsan semper. Proin laoreet lectus augue, nec sodales nunc pulvinar eu. Etiam sit amet urna nisl. Maecenas a semper nibh. Nullam viverra lorem sem. Nam a posuere erat.",
    "Suspendisse potenti. Vivamus elementum et sem non venenatis. Maecenas purus tortor, tincidunt sed interdum vel, consequat eu nulla. Aliquam eu posuere est. Vivamus maximus faucibus ex, eu molestie felis vehicula vitae. Quisque a lectus sem. Integer et semper magna, quis auctor ante. Donec quis est sit amet urna facilisis vulputate non sit amet tortor. Suspendisse potenti. Nam semper porttitor nisl, a pharetra urna iaculis nec. Aliquam fringilla metus sit amet posuere mattis. Nam elementum odio lobortis, fermentum dui eget, varius ex. Vivamus vulputate ante vel vehicula bibendum.",
    "Suspendisse potenti. Aenean fermentum volutpat dictum. Phasellus sed enim eros. Aliquam vestibulum, erat vel lacinia scelerisque, lorem felis tristique dolor, vitae venenatis urna odio sit amet purus. Mauris consectetur justo nec eros mattis tempus. Nullam porta, mauris nec condimentum finibus, est nulla maximus leo, nec lacinia est libero in elit. Praesent ac lectus molestie, tincidunt nunc eget, sodales massa. Nullam faucibus posuere turpis eget accumsan. Cras quis varius purus. Nullam at ipsum orci. Donec sodales neque non ante semper, sed finibus lorem laoreet. Etiam vitae orci pretium, eleifend velit vel, maximus nunc. Ut tincidunt, ex ut tempus congue, massa libero pretium neque, et eleifend elit elit vitae arcu.",
    "Mauris hendrerit erat et eleifend finibus. Vivamus pellentesque maximus fringilla. In hac habitasse platea dictumst. Mauris accumsan, risus at varius convallis, nulla mauris dignissim nunc, sed sollicitudin dui ipsum id dolor. Vestibulum a eleifend sem. Sed fermentum ligula ac sem placerat, eu rutrum lorem convallis. Phasellus nec velit commodo tellus ultricies gravida sed vel lectus. Aliquam malesuada luctus urna, ullamcorper efficitur mi venenatis sit amet. Suspendisse pretium rutrum imperdiet. Mauris dictum mi magna, et facilisis tellus dapibus a. Duis vitae purus condimentum, tristique elit in, porttitor mauris. Proin convallis vestibulum velit, et vestibulum arcu viverra sit amet. Aenean semper odio non dictum pellentesque. Cras molestie mattis ligula, ac vulputate nisi condimentum id. Vestibulum feugiat orci mauris",
    "Quisque tincidunt, tortor ac pellentesque congue, dui lacus ullamcorper mi, vehicula consectetur enim leo id augue. Nullam at nisi orci. In vitae nisi vitae risus faucibus tempor. Donec nibh tellus, tempor a lacus non, maximus luctus arcu. Integer porta nisi mauris, a aliquet arcu faucibus imperdiet. Suspendisse sit amet laoreet nunc, ut efficitur nisi. Mauris efficitur ante vitae magna ullamcorper dapibus. Mauris fermentum leo sed luctus cursus."
]
const form = document.querySelector(".lorem")
const amount = document.getElementById("amount")
const result = document.querySelector(".lorem-text")
form.addEventListener('submit', (e) =>{
e.preventDefault()
const value = parseInt(amount.value);

if (!value || value < 0 || value > 15) {
    result.innerHTML = `<p class = "results"> ${text[0]} </p>`;
}
else {
    let tempText = text.slice(0, value)
    tempText = tempText
    .map(function(item){
        return ` <p class="result"> ${item} </p>`;

    })
    .join("");
    result.innerHTML = tempText;
}
});